# Generated by Django 5.1.1 on 2024-09-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='factory_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
