# Generated by Django 5.1.1 on 2024-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_brand_options_alter_car_options_car_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='observations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
