# Generated by Django 5.1.1 on 2024-09-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_brand_options_alter_car_options_car_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
