# Generated by Django 5.1.1 on 2024-09-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_photo2_car_photo3_alter_car_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo2',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='photo3',
            new_name='picture',
        ),
    ]
