# Generated by Django 5.1.1 on 2024-09-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_photo2_car_foto_rename_photo3_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='car_brand', to='cars.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Pickup')], max_length=50, null=True),
        ),
    ]
